export const ADD_POKEMON_TO_LIST = 'ADD_POKEMON_TO_LIST';
export const CLEAR_POKEMON_LIST = 'CLEAR_POKEMON_LIST';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILED = 'FETCH_POKEMON_FAILED';